set_property PACKAGE_PIN L16 [get_ports A]
set_property PACKAGE_PIN J15 [get_ports B]
set_property PACKAGE_PIN H17 [get_ports F_NAND]
set_property PACKAGE_PIN K15 [get_ports F_NOR]
set_property PACKAGE_PIN J13 [get_ports F_XOR]
set_property PACKAGE_PIN N14 [get_ports F_XNOR]
set_property PACKAGE_PIN R18 [get_ports F_BUFF]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports F_BUFF]
set_property IOSTANDARD LVCMOS33 [get_ports F_NAND]
set_property IOSTANDARD LVCMOS33 [get_ports F_NOR]
set_property IOSTANDARD LVCMOS33 [get_ports F_XNOR]
set_property IOSTANDARD LVCMOS33 [get_ports F_XOR]
 